version: '3.9'

services:
  tryffle_django:
    container_name: tryffle_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
  tryffle_postgres:
    container_name: tryffle_postgres
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=tryffle
      - POSTGRES_USER=tryffle
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    