# this production does not run any postgres service it uses the common one https://github.com/pyseed/inspy_pg

services:
  tryffle_django:
    container_name: tryffle_django
    build: .
    command: make dev
    volumes:
      - .:/app
    depends_on:
      tryffle_rabbitmq:
        condition: service_healthy
      tryffle_celery:
        condition: service_healthy
      tryffle_postgres:
        condition: service_healthy
    environment:
      DJANGO_DEBUG: 0
      CELERY_BROKER_URL: amqp://guest:guest@tryffle_rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
    networks:
      - internal

  tryffle_rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - internal

  tryffle_celery:
    container_name: tryffle_celery
    build: .
    command: poetry run celery -A tryffle worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      tryffle_rabbitmq:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@tryffle_rabbitmq:5672/
      CELERY_RESULT_BACKEND: rpc://
    healthcheck:
      test: celery -b amqp://guest:guest@tryffle_rabbitmq:5672/ inspect ping
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal

  nginx:
    depends_on:
      - tryffle_django
    image: nginx:stable
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./static:/var/www/html/static
      - ./media:/var/www/html/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    # uncomment for local testing
    # DO NOT ACTIVE ON PRODUCTION SERVER
    # ports:
    #  - "8080:80"
    networks:
      - internal
      - external
    # comment traefik labels for local testing
    # KEEP THEM ON PRODUCTION SERVER (uses https://github.com/pyseed/inspy_traefik)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tryffle-web.rule=Host(`data.lunelvielalternative.com`)"
      - "traefik.http.routers.tryffle-web.entrypoints=web"
      - "traefik.http.routers.tryffle-web.middlewares=traefik-redirect"
      - "traefik.http.routers.tryffle-websecured.rule=Host(`data.lunelvielalternative.com`)"
      - "traefik.http.routers.tryffle-websecured.entrypoints=websecure"
      - "traefik.http.routers.tryffle-websecured.tls=true"
      - "traefik.http.routers.tryffle-websecured.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.tryffle-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.tryffle-auth.basicauth.users=tryffle:$$apr1$$snz3r7tu$$5RzZ7AlwJ80HhacGs7hCK1"

volumes:
  postgresdata:

networks:
  external:
    external: true
  internal:
