version: '3.3'

services:

  solar_postgres:
    container_name: solar_postgres
    image: postgres:14.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=solar
      - POSTGRES_USER=solar
      - POSTGRES_PASSWORD=secret
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - internal

  solar_maildev:
    container_name: solar_maildev
    image: maildev/maildev
    restart: unless-stopped
    networks:
      - internal

  solar_redis:
    container_name: solar_redis
    image: redis:alpine
    restart: unless-stopped
    networks:
      - internal

  solar_django:
    container_name: solar_django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    ports:
     - "8000:8000"
    volumes:
      - "./solar:/home/pythoniste"
    restart: always
    links:
      - solar_redis
      - solar_maildev
      - solar_postgres
    depends_on:
      - solar_redis
      - solar_maildev
      - solar_postgres
    environment:
      - DJANGO_DEBUG=1
      - MAILDEV_HOST=solar_maildev
      - MAILDEV_PORT=25
      - POSTGRES_HOST=solar_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=solar
      - POSTGRES_USER=solar
      - POSTGRES_PASSWORD=secret
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_SUBJECT_PREFIX=[Objectif Doc - LOCAL] 
      - EMAIL_TESTING_ADDRESS=${EMAIL_TESTING_ADDRESS}
      - SITE_URL=${SITE_URL}
    networks:
      - internal

volumes:
  postgresdata:

networks:
  internal:
