# Generated by Django 5.0 on 2024-05-31 09:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploaded_pdf.documentpdf'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentpdf',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpdf',
            name='page_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='documentpdf',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpdf',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
