# Generated by Django 5.0 on 2024-05-31 15:44

import uploaded_pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_pdf', '0002_page_document_alter_documentpdf_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=uploaded_pdf.models.page_path),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.CharField(max_length=100000),
        ),
    ]
