# Generated by Django 5.0 on 2024-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_pdf', '0003_alter_page_image_alter_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='file_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
