# Generated by Django 5.0 on 2024-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_pdf', '0004_page_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpdf',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='media/pages'),
        ),
    ]
